"""Initial schema

Revision ID: f12ab7163c34
Revises: 
Create Date: 2025-11-08 23:01:23.477700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f12ab7163c34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_telegram_chat_id', 'users', ['telegram_chat_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_chat_id'), 'users', ['telegram_chat_id'], unique=False)
    op.create_table('memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memo_user_id', 'memos', ['user_id'], unique=False)
    op.create_index(op.f('ix_memos_id'), 'memos', ['id'], unique=False)
    op.create_index(op.f('ix_memos_user_id'), 'memos', ['user_id'], unique=False)
    op.create_table('telegram_linking_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_telegram_code', 'telegram_linking_codes', ['code'], unique=False)
    op.create_index('idx_telegram_user_id', 'telegram_linking_codes', ['user_id'], unique=False)
    op.create_index(op.f('ix_telegram_linking_codes_code'), 'telegram_linking_codes', ['code'], unique=False)
    op.create_index(op.f('ix_telegram_linking_codes_user_id'), 'telegram_linking_codes', ['user_id'], unique=False)
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memo_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=False),
    sa.Column('recurrence_type', sa.String(length=20), nullable=False),
    sa.Column('recurrence_days', sa.String(length=255), nullable=True),
    sa.Column('next_trigger_time', sa.DateTime(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('user_timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['memo_id'], ['memos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alarm_memo_id', 'alarms', ['memo_id'], unique=False)
    op.create_index('idx_alarm_next_trigger_time', 'alarms', ['next_trigger_time'], unique=False)
    op.create_index(op.f('ix_alarms_id'), 'alarms', ['id'], unique=False)
    op.create_index(op.f('ix_alarms_memo_id'), 'alarms', ['memo_id'], unique=False)
    op.create_index(op.f('ix_alarms_next_trigger_time'), 'alarms', ['next_trigger_time'], unique=False)
    op.create_table('alarm_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alarm_history_alarm_id', 'alarm_history', ['alarm_id'], unique=False)
    op.create_index(op.f('ix_alarm_history_alarm_id'), 'alarm_history', ['alarm_id'], unique=False)
    op.create_index(op.f('ix_alarm_history_id'), 'alarm_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarm_history_id'), table_name='alarm_history')
    op.drop_index(op.f('ix_alarm_history_alarm_id'), table_name='alarm_history')
    op.drop_index('idx_alarm_history_alarm_id', table_name='alarm_history')
    op.drop_table('alarm_history')
    op.drop_index(op.f('ix_alarms_next_trigger_time'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_memo_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_id'), table_name='alarms')
    op.drop_index('idx_alarm_next_trigger_time', table_name='alarms')
    op.drop_index('idx_alarm_memo_id', table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_telegram_linking_codes_user_id'), table_name='telegram_linking_codes')
    op.drop_index(op.f('ix_telegram_linking_codes_code'), table_name='telegram_linking_codes')
    op.drop_index('idx_telegram_user_id', table_name='telegram_linking_codes')
    op.drop_index('idx_telegram_code', table_name='telegram_linking_codes')
    op.drop_table('telegram_linking_codes')
    op.drop_index(op.f('ix_memos_user_id'), table_name='memos')
    op.drop_index(op.f('ix_memos_id'), table_name='memos')
    op.drop_index('idx_memo_user_id', table_name='memos')
    op.drop_table('memos')
    op.drop_index(op.f('ix_users_telegram_chat_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_telegram_chat_id', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
